image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build_and_push

before_script:
  # Login to Docker Hub
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build_and_push_images:
  stage: build_and_push
  script:
    - docker build -t $DOCKERHUB_USERNAME/flink-job ./flink-job
    - docker push $DOCKERHUB_USERNAME/flink-job

    - docker build -t $DOCKERHUB_USERNAME/kafka-producer ./kafka-producer
    - docker push $DOCKERHUB_USERNAME/kafka-producer

    - docker build -t $DOCKERHUB_USERNAME/node-backend ./node-backend
    - docker push $DOCKERHUB_USERNAME/node-backend

    - docker build -t $DOCKERHUB_USERNAME/frontend ./frontend
    - docker push $DOCKERHUB_USERNAME/frontend
