image:
  name: gcr.io/kaniko-project/executor:latest
  entrypoint: [""]

variables:
  DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
  DOCKERHUB_TOKEN: $DOCKERHUB_TOKEN
  DOCKER_REGISTRY: docker.io
  DOCKER_CONFIG: /kaniko/.docker/

stages:
  - build_and_push

build_and_push_flink_job:
  stage: build_and_push
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ./flink-job --dockerfile ./flink-job/Dockerfile --destination $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/flink-job:latest

build_and_push_kafka_producer:
  stage: build_and_push
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ./kafka-producer --dockerfile ./kafka-producer/Dockerfile --destination $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/kafka-producer:latest

build_and_push_node_backend:
  stage: build_and_push
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ./node-backend --dockerfile ./node-backend/Dockerfile --destination $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/node-backend:latest

build_and_push_frontend:
  stage: build_and_push
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ./frontend --dockerfile ./frontend/Dockerfile --destination $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/frontend:latest
